### ISSUE TITLE
make dependency of python2 explicit. 

### ISSUE THREAD

**Issue by cryptointerest** [jenom/pdfbook2#2]
pdfbook2 requires python2. When calling this on archlinux, one first gets an error and the first line

`#!/usr/bin/env python`

needs to be changed to

` #!/usr/bin/env python2`

to make it work. Could this maybe be be corrected upstream? I've seen bugreports about this on fedora's bugzilla, but should every distro really fix this themselves?

**Comment by jenom** [comment]
I migrated to python3 with implicit dependency as suggested.
